site_name: QuantGov
theme: readthedocs
pages:
    - Home: 'index.markdown'
    - Architecture: 'architecture.markdown'
    - Corpus: 'corpus.markdown'
    - Estimator: 'estimator.markdown'
    - Project: 'project.markdown'
    - Databank: 'databank.markdown'
