site_name: QuantGov Documentation
site_url: http://docs.quantgov.org
theme: readthedocs
google_analytics: ["UA-86588008-2", "auto"]
repo_url: https://github.com/quantgov/documentation
nav:
  - "index.markdown"
  - Tutorial:
      - "tutorial/introduction.markdown"
      - "tutorial/prerequisites.markdown"
      - "tutorial/first_corpus.markdown"
      - "tutorial/corpus_analysis.markdown"
      - "tutorial/first_estimator.markdown"
      - "tutorial/first_project.markdown"
  - "corpus.markdown"
  - "nlp.markdown"
  - "ml.markdown"
markdown_extensions:
  - smarty
